### ISSUE TITLE
Add a mod for translations? intllib?

### ISSUE THREAD

**Issue by LNJplus** [BlockMen/minetest_next#25]
Would you agree to add the intllib?

I'd like to help to translate (to German)!

**Comment by BlockMen** [comment]
No, i would not agree, sorry.
The problem is, that it is translated server-side, and the server doesn't know which language should be sent to client, so it will be wrong in a lot cases in multiplayer.

This should be done by the engine itself or by clientside mods (when added to engine). There should be some feature request for the engine already, don't know the number though.

**Comment by LNJplus** [comment]
I agree that we should use a client side mod or functions from the engine (both when added).

I think I can close this.
