### ISSUE TITLE
Birches? Meliaceae Trees?

### ISSUE THREAD

**Issue by LNJplus** [BlockMen/minetest_next#28]
Some time ago a made a birch mod (and a maple/red maple). I never made it public.
Maybe you like it!

Here is a screenshot:
![](http://i.imgur.com/mQbEzxh.jpg)
The textures are made by JBB (he is in the mt forum too)

But I think it would be good to make new form in the L-system or as schematic.

And I think that we need in MT NeXt a dark wood, because the junglewood is bright.
JBB thought about [Meliaceae Trees](https://en.wikipedia.org/wiki/Meliaceae).
And in German: [Mahagonibäume](https://de.wikipedia.org/wiki/Mahagonigew%C3%A4chse)
![](https://upload.wikimedia.org/wikipedia/commons/9/90/Neem.jpg)

This wouldn't be so usualy.

And I like [Populus](https://en.wikipedia.org/wiki/Populus) too.
I like trees,  so I want more (and I don't think that they from mt_game add a new type so soon).

**Comment by BlockMen** [comment]
I'm not in general against other trees, but there are few thoughts on it:

- New trees should be generated by mapgen, so what tree should be spawned in which biome. Also how much, as only tree in that biome or as "extra" tree.

- Jungletree textures were mainly reverted since the way they were changed is bad. Keeping the side textures and trying to force a dark wood in it looks horrible. The light one might not look the best, but it is consistent. So i would prefer a better junglewood concept instead of adding a new tree.

- Maybe instead of a new tree some other plant that could be usefull? or a real special (very rare) tree that is really huge??

**Comment by LNJplus** [comment]
I also had bushes in mind.
With a small fence like stem (one node height) and some (bush) leaves around it.

I really like the idea with the huge tree! :+1: 

:smiley:

**Comment by LNJplus** [comment]
I uploaded the birch mod to GitHub!
Here it is:
https://github.com/LNJplus/birch

**Comment by BlockMen** [comment]
Birches added: 607734a8fc6c72acfef21f1de134474ccbf8b0bc and 60fe6d1d5140faba44c0511e5969ad8ecdeb8a4a

**Comment by LNJplus** [comment]
Nice! :D
